# Generated by Django 5.2.6 on 2025-09-21 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative_roll', models.IntegerField()),
                ('initiative_bonus', models.IntegerField()),
                ('initiative_total', models.IntegerField()),
                ('initiative_round', models.IntegerField(default=0)),
                ('current_turn', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='rooms.room')),
            ],
            options={
                'ordering': ['-initiative_total', 'character__name'],
                'unique_together': {('room', 'character', 'initiative_round')},
            },
        ),
    ]
